FROM registry.fedoraproject.org/fedora:latest@sha256:32f0781a3205b801b333386d7f31aeba47c0639e68f3b7248a304b41a7933d2b

COPY mock-wrapper /usr/bin

RUN dnf install -y mock rpmdevtools rpkg copr-cli rpmlint && dnf clean all

ENTRYPOINT ["/usr/bin/mock-wrapper"]
